import time
from pathlib import Path
from playwright.sync_api import expect, sync_playwright


artifacts = Path("evidence/screenshots")
artifacts.mkdir(parents=True, exist_ok=True)

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=True)
    page = browser.new_page(viewport={"width": 1440, "height": 1000})
    console_errors = []
    page.on("console", lambda message: console_errors.append(message.text) if message.type == "error" else None)

    page.goto("http://127.0.0.1:3000")
    page.wait_for_load_state("networkidle")
    expect(page.locator("html")).to_have_attribute("lang", "en")
    expect(page.locator("#stat-regulations")).to_have_text("22")
    expect(page.locator("#stat-articles")).to_have_text("26")
    expect(page.locator("#latest-updates .signal-item")).to_have_count(5)
    expect(page.locator("#latest-updates .signal-item").first.locator("time")).to_have_text("2026.03.02")
    expect(page.locator("#latest-updates .signal-item").first).to_contain_text("S 86/2026")
    expect(page.locator("#latest-updates")).not_to_contain_text("2024.11.05")
    expect(page.locator("#latest-updates")).not_to_contain_text("HKMA updates technology-risk expectations")
    page.screenshot(path=artifacts / "01-home-en.png", full_page=True)

    page.get_by_role("link", name="Library", exact=True).click()
    page.locator('[data-jurisdiction="SG"]').click()
    expect(page.locator(".reg-card")).to_have_count(12)
    page.locator("#industry-filter").select_option("financial_services")
    expect(page.locator(".reg-card")).to_have_count(3)
    page.locator("#industry-filter").select_option("")
    page.locator("#reg-search").fill("breach")
    expect(page.locator(".reg-card")).to_have_count(4)
    page.screenshot(path=artifacts / "02-library-filtered-en.png", full_page=True)
    page.locator("#reg-search").fill("")
    expect(page.locator(".reg-card")).to_have_count(12)
    page.locator('[data-regulation-id="reg_sg_pdpr_2021"]').click()
    expect(page.locator("#detail-overlay")).to_be_visible()
    expect(page.locator("#detail-title")).to_have_text("Personal Data Protection Regulations 2021")
    expect(page.locator("#detail-content")).to_contain_text("2026-03-02")
    expect(page.locator("#detail-content .official-button")).to_be_visible()
    page.screenshot(path=artifacts / "03-regulation-detail-en.png", full_page=True)
    page.locator("#detail-close").click()
    expect(page.locator("#detail-overlay")).to_be_hidden()

    page.locator('[data-jurisdiction="HK"]').click()
    expect(page.locator(".reg-card")).to_have_count(10)
    page.locator('[data-regulation-id="reg_hk_hkma_tmg1"]').click()
    expect(page.locator("#detail-title")).to_contain_text("TM-G-1")
    expect(page.locator("#detail-content")).to_contain_text("2003-06-24")
    expect(page.locator("#detail-content")).not_to_contain_text("2024-11-05")
    page.screenshot(path=artifacts / "03b-hkma-tmg1-detail-en.png", full_page=True)
    page.locator("#detail-close").click()

    page.locator('[data-regulation-id="reg_hk_id_compliance_guide_2024"]').click()
    expect(page.locator("#detail-title")).to_have_text("Code of Practice on the Identity Card Number and other Personal Identifiers: Compliance Guide for Data Users")
    expect(page.locator("#detail-content")).to_contain_text("2024-08-22")
    expect(page.locator("#detail-content")).to_contain_text("April 2016 HKID Code of Practice")
    page.screenshot(path=artifacts / "03c-hkid-compliance-guide-en.png", full_page=True)
    page.locator("#detail-close").click()

    page.get_by_role("link", name="Timeline", exact=True).click()
    page.locator('[data-timeline-jurisdiction="SG"]').click()
    expect(page.locator("#timeline-list .timeline-item")).to_have_count(8)
    expect(page.locator("#timeline-list .timeline-item").first.locator(".timeline-date")).to_have_text("2026.03.02")
    page.screenshot(path=artifacts / "04-timeline-en.png", full_page=True)
    page.locator('[data-timeline-jurisdiction="HK"]').click()
    expect(page.locator("#timeline-list .timeline-item")).to_have_count(8)
    expect(page.locator("#timeline-list")).to_contain_text("2003.06.24")
    expect(page.locator("#timeline-list")).not_to_contain_text("2024.11.05")
    page.screenshot(path=artifacts / "04b-timeline-hk-en.png", full_page=True)

    page.locator("#language-toggle").click()
    expect(page.locator("html")).to_have_attribute("lang", "zh-CN")
    expect(page.get_by_role("link", name="订阅信号 ↗", exact=True)).to_be_visible()
    page.get_by_role("link", name="订阅信号 ↗", exact=True).click()
    email = f"ui-{int(time.time())}@example.com"
    page.locator("#email").fill(email)
    page.locator("#subscription-form button[type=submit]").click()
    expect(page.locator("#subscription-feedback")).to_contain_text("持久保存")
    expect(page.locator("#manage-actions")).to_be_visible()
    page.locator("#daily-briefing").uncheck()
    # 法域多选（对接 /api/jurisdictions）：默认全选；取消 HK 后仅保留 SG。
    page.locator('[data-jurisdiction-choice="HK"]').click()
    expect(page.locator('[data-jurisdiction-choice="HK"]')).to_have_attribute("aria-pressed", "false")
    expect(page.locator('[data-jurisdiction-choice="SG"]')).to_have_attribute("aria-pressed", "true")
    page.locator("#subscription-form button[type=submit]").click()
    expect(page.locator("#subscription-feedback")).to_contain_text("持久保存")
    # 「全选」切换恢复全选，验证多选切换。
    page.locator('[data-jurisdiction-all="1"]').click()
    expect(page.locator('[data-jurisdiction-choice="HK"]')).to_have_attribute("aria-pressed", "true")
    expect(page.locator('[data-jurisdiction-choice="SG"]')).to_have_attribute("aria-pressed", "true")
    page.screenshot(path=artifacts / "05-subscription-zh.png", full_page=True)
    page.locator("#unsubscribe-button").click()
    expect(page.locator("#subscription-feedback")).to_contain_text("订阅已取消")

    page.set_viewport_size({"width": 390, "height": 844})
    page.goto("http://127.0.0.1:3000")
    page.wait_for_load_state("networkidle")
    page.locator(".menu-button").click()
    expect(page.locator(".topbar nav")).to_be_visible()
    page.screenshot(path=artifacts / "06-mobile-navigation.png", full_page=True)

    assert not console_errors, f"Browser console errors: {console_errors}"
    print("UI_OK i18n=en-default+zh-toggle home=22/26 latest=pdpr-2026 library_sg=12 finance_sg=3 search=4 details=pdpr+hkma+hkid timeline_sg=8 timeline_hk=8 jurisdictions=multi-select subscription=create-update-cancel mobile_nav=ok")
    browser.close()
